/*
 * doorCam_menager.c
 *
 *  Source code for managing doorCam project with freeRTOS
 *
 *  Created on: Jun 2, 2024
 *      Author: tomas
 */

#include "Custom/doorCam_manager.h"

//
QueueHandle_t qProxTrigQueue;
osThreadId defaultTaskHandle;


void vDoorCamInit(void){
	MX_GPIO_Init();
	SystemClock_Config();
	MX_SPI1_Init();
}


void vDoorCamProciessing(void){

	//Queue reacting on proximity sensor trigger, used to determine start and stop of SPI transmition
	qProxTrigQueue = xQueueCreate(QUEUE_LENGHT, sizeof(uint8_t));


	//Default thread, generated by IDE while introducing freeRTOS to the project
	osThreadDef(defaultTask, StartDefaultTask, osPriorityNormal, 0, 128);
	defaultTaskHandle = osThreadCreate(osThread(defaultTask), NULL);

	if(qProxTrigQueue != NULL){
		xTaskCreate(vSPITestTask, 			 /* Pointer to the function that implements the task.*/
					"SPI testing task",		 /* Text name for the task. */
					DEFAULT_TASK_SIZE,		 /* Size of task stack memory in words*/
					NULL,					 /* Task parameter if used */
					DEFAULT_TASK_PRIORITY,	 /* This task will run at priority 1. */
					NULL					 /* Task handle for future API calls if needed*/
					);

		xTaskCreate(vPoroxSensMeasureTask, 						 /* Pointer to the function that implements the task.*/
					"Proximity sensor measurement task",		 /* Text name for the task. */
					DEFAULT_TASK_SIZE,							 /* Size of task stack memory in words*/
					NULL,										 /* Task parameter if used */
					DEFAULT_TASK_PRIORITY,	 					 /* This task will run at priority 1. */
					NULL					 					 /* Task handle for future API calls if needed*/
					);
	}
	else{
		vErroLEDChangeState();
	}


	osKernelStart();


}


/* SPI test, if transmition occurs correctly LD3 should blink, it there is an errors - LD4 should blink */
void vSPITestTask(void* pvParameters) {

	if(bSPITransmisionTest()){
		vLEDChangeState();
		xTaskDelay(150);
	}
	else{
		vErrorLEDChangeState();
		xTaskDelay();
	}
}


/*Proximity sensor managing task. Error should trigger LD4, see vProxSensMeasure TODO:FINISH THE METHOD*/
void vPoroxSensMeasureTask(void* pvParameters) {
	xTickType tTickStartOfMeasurement, tTickTimeOfMeasurment;
	uint8_t iSenorState;

	iSensorState = vProxSensMeasure();

	if(iSensorState == SENSOR_STARTING){
		//Start of measurement in tick
		tTickStartOfMeasurement = xTickGetCount();
	}
	else if(iSensorState == SENSOR_MEASURE_FINNISHED){
		//Time of full measurement in ticks
		tTickTimeOfMeasurment = xTickGetCount() - tStartOfMeasurement;


	}
	else if(iSensorState == SENSOR_ERROR){
		xTaskDelay(500);
	}

}

//Default task created by IDE while introducing freeRTOS
void StartDefaultTask(void* pvParameters)
{
  /* USER CODE BEGIN 5 */
  /* Infinite loop */
  for(;;)
  {
    osDelay(1);
  }
  /* USER CODE END 5 */
}
