/*
 * doorCam_menager.c
 *
 *  Source code for managing doorCam project with freeRTOS
 *
 *  Created on: Jun 2, 2024
 *      Author: tomas
 */


#include "Custom/doorCam_manager.h"
#include "Custom/GPIOHandler.h"
#include "Custom/SystemClockConfig.h"
#include "Custom/SPIHandler.h"
#include "Custom/proxSensHandler.h"
#include "cmsis_os.h"

#include <stm32f0xx_hal.h>
#include <stdint.h>


//Structures used for freeRTOS features:
QueueHandle_t vProxTrigQueue;
osThreadId defaultTaskHandle;


void vDoorCamProciessing(void);
void vDoorCamInit(void);
void vSPITestTask(void* pvParameters);
void vProxSensMeasureTask(void* pvParameters);
void StartDefaultTask(void* pvParameters);


//Function initializing all required components of doorCam
void vDoorCamInit(void){
	MX_GPIO_Init();
	SystemClock_Config();
	MX_SPI1_Init();
}

//Main function for processing all features in doorCam
void vDoorCamProciessing(void){

	//Queue reacting on proximity sensor trigger, used to determine start and stop of SPI transmition
    vProxTrigQueue = xQueueCreate(QUEUE_LENGHT, sizeof(uint32_t));


	//Default thread, generated by IDE while introducing freeRTOS to the project
	osThreadDef(defaultTask, StartDefaultTask, osPriorityNormal, 0, 128);
	defaultTaskHandle = osThreadCreate(osThread(defaultTask), NULL);

	if(vProxTrigQueue != NULL){
		xTaskCreate(vSPITestTask, 			 /* Pointer to the function that implements the task.*/
					"SPI testing task",		 /* Text name for the task. */
					DEFAULT_TASK_SIZE,		 /* Size of task stack memory in words*/
					NULL,					 /* Task parameter if used */
					DEFAULT_TASK_PRIORITY,	 /* This task will run at priority 1. */
					NULL					 /* Task handle for future API calls if needed*/
					);

		xTaskCreate(vProxSensMeasureTask, 						 /* Pointer to the function that implements the task.*/
					"Proximity sensor measurement task",		 /* Text name for the task. */
					DEFAULT_TASK_SIZE,							 /* Size of task stack memory in words*/
					NULL,										 /* Task parameter if used */
					DEFAULT_TASK_PRIORITY,	 					 /* This task will run at priority 1. */
					NULL					 					 /* Task handle for future API calls if needed*/
					);
	}
//	else{
//		vErrorLEDChangeState();
//	}


	osKernelStart();


}

/* SPI test, if transmition occurs correctly LD3 should blink, it there is an errors - LD4 should blink */
void vSPITestTask(void* pvParameters) {
	BaseType_t xStatus;
	uint32_t iQueueValue;

	for(;;)
	{
		//xStatus = xQueueReceive(vProxTrigQueue, &iQueueValue, WAIT_TIME);

//		if(xStatus != pdPASS){
//			vErrorLEDOn();
//			vTaskDelay(ERROR_WAIT_TIME);
//		}
//		else{
//			if(bSPITransmisionTest()){
//					if(bLEDGetState()){
//						vLEDOff();
//					}
//					else if (!bLEDGetState()){
//						vLEDOn();
//					}
//					vTaskDelay(WAIT_TIME);
//				}
//				else{
//					//vErrorLEDChangeState();
//					vTaskDelay(ERROR_WAIT_TIME);
//				}
//			vErrorLEDOff();
//		}
	}


}


/*Proximity sensor managing task. Error should trigger LD4, see vProxSensMeasure*/
void vProxSensMeasureTask(void* pvParameters) {
	uint32_t iMockupTrigger = 1;
	BaseType_t xStatus;

	for(;;)
	{
		if(!bUserButtonGetState()) continue;

		xStatus = xQueueSendToBack(vProxTrigQueue, &iMockupTrigger , 0);

		if(xStatus == pdPASS)
		{
			vLEDOn();
			if(bErrorLEDGetState())
			{
				vErrorLEDOff();
				vTaskDelay(ERROR_WAIT_TIME);
			}
			continue;
		}
		vErrorLEDOn();
		vTaskDelay(WAIT_TIME);

	}
}

//Default task created by IDE while introducing freeRTOS

void StartDefaultTask(void* pvParameters)
{

  for(;;)
  {
    osDelay(1);
  }
}
